pipeline:
  lint:
    image: cubyn/node:ci-7
    commands:
      - make deps
      - make lint
  test:
    image: cubyn/node:ci-7
    commands:
      - AMQP_HOST=broker:5672 make test-cover
    when:
      status: [ success, failure ]

services:
  broker:
    image: rabbitmq:3.6-alpine
